version: "3.8"

services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      VERSION: "snapshot"
    volumes:
      - ./data:/data
