ersion: "3.8"

services:
  forge-minecraft:
    image: itzg/minecraft-server:latest
    ports:
      - ":25565:25565" # using tailscale config (see README) | adjust port mapping accordingly if using multiple servers
    environment:
      EULA: "TRUE"
      TYPE: "FORGE" # adjust the mod type
      VERSION: "1.20.1"  # adjust to match your mods
      FORGE_VERSION: "47.4.1"  # optional, can auto-detect from VERSION
      MEMORY: "8G" # adjust the memory allocation
    volumes:
      - ./data:/data
      - ./mods:/mods
